# Site settings
title: Emilio's Profile
email: emiliogomezlavin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer * Marketeer * Musician
baseurl: "/"
url: "http://emiliogomezlavin.github.io"
twitter_username: @emiliogomlav
github_username:  emiliogomezlavin
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
